alter table products add column output_weight varchar(20);

update products set output_weight = '0,250' where name = 'Капучино';
update products set output_weight = '0,300' where name = 'Американо';
update products set output_weight = '0,350' where name = 'Латте';
update products set output_weight = '0,400' where name = 'Паста болоньезе';
update products set output_weight = '0,300' where name = 'Стейк рибай';
update products set output_weight = '0,350' where name = 'Борщ';
update products set output_weight = '0,250' where name = 'Солянка';
update products set output_weight = '0,180' where name = 'Куриный бульон';
update products set output_weight = '0,320' where name = 'Бургер классик';
update products set output_weight = '0,280' where name = 'Куриные крылья';
update products set output_weight = '0,350' where name = 'Том Ям';
update products set output_weight = '0,250' where name = 'Лосось на гриле';
update products set output_weight = '0,550' where name = 'Маргарита';
update products set output_weight = '0,580' where name = 'Пепперони';
update products set output_weight = '0,600' where name = '4 сыра';
update products set output_weight = '0,550' where name = 'Диабло';
update products set output_weight = '0,520' where name = 'Гавайская';
update products set output_weight = '0,650' where name = 'Мясная';
update products set output_weight = '0,200' where name = 'Цезарь';
update products set output_weight = '0,220' where name = 'Греческий';
update products set output_weight = '0,180' where name = 'Оливье';
update products set output_weight = '0,190' where name = 'Витаминный';
update products set output_weight = '0,250' where name = 'Тёплый с курицей';
update products set output_weight = '0,250' where name = 'Свинина';
update products set output_weight = '0,200' where name = 'Курица' and category_id = (select id from categories where name = 'Шашлык' limit 1);
update products set output_weight = '0,280' where name = 'Баранина';
update products set output_weight = '0,220' where name = 'Люля-кебаб';
update products set output_weight = '0,150' where name = 'Наггетсы';
update products set output_weight = '0,180' where name = 'Мини-бургер';
update products set output_weight = '0,200' where name = 'Сырники';
update products set output_weight = '0,180' where name = 'Фалафель';
update products set output_weight = '0,150' where name = 'Хумус';
update products set output_weight = '0,350' where name = 'Боул с киноа';
